# Select which component to install
component:
  master: true
  datanode: true
  metanode: true
  objectnode: true
  client: true
  provisioner: true
  monitor: true
  # The console component was deprecated.
  console: false
  ingress: true

# Allow to override kubernetes version
kubernetes:
  version: ""

image:
  server: chubaofs/cfs-server:2.4.0
  client: chubaofs/cfs-client:2.4.0
  csi_driver: chubaofs/cfs-csi-driver:2.4.0.110.4
  csi_provisioner: quay.io/k8scsi/csi-provisioner:v1.6.0
  driver_registrar: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
  csi_attacher: quay.io/k8scsi/csi-attacher:v2.0.0
  grafana: grafana/grafana:6.4.4
  prometheus: prom/prometheus:v2.13.1
  consul: consul:1.6.1
  pull_policy: "IfNotPresent"

log:
  # Do not redirect the standard output into a file, recommend to
  # set to true, but cfs-server version > 3.2.0 was required
  do_not_redirect_std: false

# store data,log and other data, these directory will be
#  mounted from host to container using hostPath
path:
  data: /var/lib/chubaofs
  log: /var/log/chubaofs
  monitor: /var/lib/chubaofs_prometheus

master:
  # The replicas of master component, at least 3, recommend to be an odd number
  replicas: 3
  # Cluster name
  cluster: my-cluster
  # NodeSelector
  nodeSelector:
    "component.cubefs.io/master": "enabled"
  tolerations: [ ]
  host: master.chubaofs.com
  log_level: error
  retain_logs: 2000
  # Master service http port
  port: 17010
  # Master golang pprof port
  prof: 17020
  exporter_port: 9500
  # Reserved memory in bytes for each metanode, if available memory less than this value, the metanode will be unwritable
  metanode_reserved_mem: "67108864"
  resources:
    enabled: false
    requests:
      memory: "8Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "8000m"

metanode:
  # NodeSelector for metanode daemonset
  nodeSelector:
    "component.cubefs.io/metanode": "enabled"
  tolerations: [ ]
  log_level: error
  # Total memory metanode can use, recommended to be configured
  # as 80% of physical machine memory
  total_mem: "26843545600"
  port: 17210
  prof: 17220
  raft_heartbeat: 17230
  raft_replica: 17240
  exporter_port: 9510
  resources:
    enabled: true
    requests:
      memory: "32Gi"
      cpu: "2000m"
    limits:
      memory: "256Gi"
      cpu: "8000m"

datanode:
  # NodeSelector for datanode daemonset
  nodeSelector:
    "component.cubefs.io/datanode": "enabled"
  tolerations: [ ]
  log_level: error
  port: 17310
  prof: 17320
  raft_heartbeat: 17330
  raft_replica: 17340
  exporter_port: 9520
  # Disks will be used by datanode to storage data
  # Format: disk_mount_point:reserved_space
  # disk_mount_point: the mount point of disk in machine
  # reserved_space: similar to metanode reserved space, if disk available
  # space less than this number, then the disk will be unwritable
  disks:
    - /data0:21474836480
    - /data1:21474836480
  resources:
    enabled: false
    requests:
      memory: "8Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "8000m"

objectnode:
  # The replicas of object component, object node is stateless,
  # it can be any number depending on your traffic magnitude.
  replicas: 3
  log_level: error
  port: 1601
  prof: 7011
  exporter_port: 9500
  nodeSelector:
    "component.cubefs.io/objectnode": "enabled"
  tolerations: [ ]
  region: "spark"
  # Domains listed here will be used in resolution of pan-domain names to parse bucket name
  domains: "objectcfs.jd.local,objectnode.cfs.jd.local"
  host: objectnode.chubaofs.com
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

client:
  replicas: 1
  vol_name: "test"
  owner: "chubaofs"
  log_level: error
  exporter_port: 9530
  prof: 17410
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

provisioner:
  dirver_name: csi.chubaofs.com
  log_level: error
  kubelet_path: /var/lib/kubelet

console:
  replicas: 1
  log_level: error
  port: 1602
  # Ingress host name
  host: console.chubaofs.com
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

consul:
  port: 8500
  replicas: 1
  external_address: ""

grafana:
  port: 3000
  replicas: 1
  # Ingress host name
  host: monitor.chubaofs.com
  admin_password: !!string 123456
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

prometheus:
  port: 9090
  replicas: 1
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

storageClass:
  default: false
