{{- if .Values.component.provisioner }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: cfs-csi-node
  namespace: {{ $namespace }}
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: cfs-csi-node
  template:
    metadata:
      labels:
        app: cfs-csi-node
    spec:
      serviceAccount: cfs-csi-service-account
      nodeSelector:
        chubaofs-csi-node: enabled
      containers:
        - name: driver-registrar
          image: {{ $.Values.image.driver_registrar }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          securityContext:
            privileged: true
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --kubeconfig=/etc/kubernetes/config
          env:
            - name: ADDRESS
              value: {{ $.Values.provisioner.kubelet_path -}}/plugins/csi.chubaofs.com/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ $.Values.provisioner.kubelet_path -}}/plugins/csi.chubaofs.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/kubelet/plugins/csi.chubaofs.com
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
            - name: kube-config
              mountPath: /etc/kubernetes
        - name: cfs-driver
          image: {{ $.Values.image.csi_driver }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          securityContext:
            privileged: true
          command:
            - /bin/tini
            - "--"
            - bash
            - "-c"
            - |-
              set -e
              su -p -s /bin/bash -c "/cfs/bin/start.sh &"
              su -p -s /bin/bash -c "sleep 9999999d"
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: KUBE_CONFIG
              value: /etc/kubernetes/config
            - name: LOG_LEVEL
              value: "5"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: DRIVER_NAME
              value: {{ $.Values.provisioner.dirver_name }}
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - name: kube-config
              mountPath: /etc/kubernetes
      volumes:
        - hostPath:
            path: {{ $.Values.provisioner.kubelet_path -}}/plugins/csi.chubaofs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: {{ $.Values.provisioner.kubelet_path -}}/plugins
            type: Directory
          name: registration-dir
        - hostPath:
            path: {{ $.Values.provisioner.kubelet_path -}}/pods
            type: Directory
          name: mountpoint-dir
        - configMap:
            name: csi-kube-config
          name: kube-config
---
{{ end }}
