{{- if .Values.component.client }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
{{ tuple $envAll $namespace "client" | include "helm-toolkit.metadata_labels" | indent 4 }}
  namespace: {{ $namespace }}
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
{{ tuple $envAll $namespace "client" | include "helm-toolkit.metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll $namespace "client" | include "helm-toolkit.metadata_labels" | indent 8 }}
    spec:
      initContainers:
        - name: check-master-service
          image: {{ $.Values.image.client }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          command: [ "/bin/bash", "/cfs/bin/check-master-service.sh" ]
          env:
            - name: CBFS_MASTER_SERVICE_PORT
              value: {{ include "chubaofs.master-service.with.port" . | quote }}
          volumeMounts:
            - name: chubaofs-bin
              mountPath: /cfs/bin/check-master-service.sh
              subPath: check-master-service.sh
              readOnly: true
        - name: init-config
          image: {{ $.Values.image.client }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          command: [ "/bin/bash", "/cfs/bin/config-client.sh" ]
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: CBFS_CLIENT_PROF
              value: {{ .Values.client.prof | quote }}
            - name: CBFS_CLIENT_LOG_LEVEL
              value: {{ .Values.client.log_level | quote }}
            - name: CBFS_MASTER_ADDRS
              value: {{ include "chubaofs.master.address.array" . | quote }}
            - name: CBFS_CLIENT_VOL_NAME
              value: {{ .Values.client.vol_name | quote }}
            - name: CBFS_CLIENT_OWNER
              value: {{ .Values.client.owner | quote }}
            - name: CBFS_CLIENT_EXPORTER_PORT
              value: {{ .Values.client.exporter_port | quote }}
            - name: CBFS_CONSUL_ADDR
              value: {{ tuple $envAll | include "chubaofs.monitor.consul.url" | quote }}
          volumeMounts:
            - name: chubaofs-bin
              mountPath: /cfs/bin/config-client.sh
              subPath: config-client.sh
              readOnly: true
            - name: chubaofs-conf
              mountPath: /cfs/conf
        - name: init-volume
          image: {{ $.Values.image.client }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          command: [ "/bin/bash", "/cfs/bin/check-volumn.sh" ]
          securityContext:
            privileged: true
          env:
            - name: CBFS_CLIENT_VOL_NAME
              value: {{ .Values.client.vol_name | quote }}
            - name: CBFS_CLIENT_OWNER
              value: {{ .Values.client.owner | quote }}
            - name: CBFS_MASTER_SERVICE_PORT
              value: {{ include "chubaofs.master-service.with.port" . | quote }}
          volumeMounts:
            - name: chubaofs-bin
              mountPath: /cfs/bin/check-volumn.sh
              subPath: check-volumn.sh
              readOnly: true
      containers:
        - name: client-pod
          image: {{ $.Values.image.client }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/bash", "/cfs/bin/start.sh" ]
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
{{ tuple $envAll "prof" .Values.client.prof | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "exporter-port" .Values.client.exporter_port | include "helm-toolkit.utils.container_port" | indent 12 }}
          volumeMounts:
            - name: chubaofs-bin
              mountPath: /cfs/bin/start.sh
              subPath: start-client.sh
              readOnly: true
            - name: chubaofs-conf
              mountPath: /cfs/conf
            {{- if $.Values.path.log }}
            - name: pod-log-path
              mountPath: /cfs/logs
              readOnly: false
            {{- end }}
            {{- if $.Values.path.data }}
            - name: pod-data-path
              mountPath: /cfs/data
              readOnly: false
            {{- end }}
{{ tuple $envAll $envAll.Values.client.resources | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
      volumes:
        - name: chubaofs-bin
          configMap:
            name: chubaofs-bin
            defaultMode: 0555
        - name: chubaofs-conf
          emptyDir: {}
        {{- if $.Values.path.log }}
        - name: pod-log-path
          hostPath:
            path: {{ $.Values.path.log }}
        {{- end }}
        {{- if $.Values.path.data }}
        - name: pod-data-path
          hostPath:
            path: {{ $.Values.path.data }}
        {{- end }}
{{ end }}





