{{- if .Values.component.objectnode }}
{{- $envAll := . }}

---
apiVersion: v1
kind: Service
metadata:
  name: objectnode-service
  
spec:
  ports:
    - port: {{ .Values.objectnode.port }}
      protocol: TCP
      targetPort: {{ .Values.objectnode.port }}
  selector:
{{ tuple $envAll .Release.Namespace "objectnode" | include "helm-toolkit.metadata_labels" | indent 4 }}
{{ end }}