{{- if .Values.component.monitor }}
{{- $envAll := . }}

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  
spec:
  ports:
    - port: {{ .Values.grafana.port }}
      protocol: TCP
      targetPort: {{ .Values.grafana.port }}
  selector:
{{ tuple $envAll .Release.Namespace "grafana" | include "helm-toolkit.metadata_labels" | indent 4 }}
{{ end }}