# Configmap cubefs-config-override is used to specify
# config for some specific node, seems not all the nodes
# configuration will be same.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cubefs-config-override
data:
  # Format: "${Node_IP}":${JSON_CONFIG}
  # There's a demo server config 1.1.1.1 left for example,
  # All the config written here will be merged to the final
  # '/cfs/conf/datanode.json' file.
  datanode.json: |+
    {
      "1.1.1.1": {
        "logDir": "/data/cfs/log",
        "disks": [
          "/disk/nvme0n1:59000000000",
          "/disk/nvme1n1:59000000000",
          "/disk/nvme2n1:59000000000"
        ]
      }
    }
  # Similar to datanode config.
  metanode.json: |+
    {}