{{- if .Values.component.provisioner }}
{{- $envAll := . }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-kube-config
data:
  config: |+
{{ .Files.Get "config/kubeconfig" | indent 4 }}
---
{{ end }}