{{- if .Values.component.master }}
{{- $envAll := . }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
  labels:
{{ tuple $envAll .Release.Namespace "master" | include "helm-toolkit.metadata_labels" | indent 4 }}

spec:
  updateStrategy:
    type: OnDelete
  replicas: {{ .Values.master.replicas }}
  serviceName: master-service
  selector:
    matchLabels:
{{ tuple $envAll .Release.Namespace "master" | include "helm-toolkit.metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll .Release.Namespace "master" | include "helm-toolkit.metadata_labels" | indent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
    {{- with .Values.master.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.master.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      # Master can not deploy in a same node, port will conflict.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/application
                    operator: In
                    values:
                      - {{ .Release.Namespace }}
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - "master"
              topologyKey: kubernetes.io/hostname
      hostNetwork: true
      priorityClassName: cubefs-high-priority
      hostPID: false
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: init-config
          image: {{ $.Values.image.server }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          command: [ "/bin/bash", "/cfs/bin/config-master.sh" ]
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: CBFS_MASTER_CLUSTER
              value: {{ .Values.master.cluster }}
            - name: CBFS_MASTER_PORT
              value: {{ .Values.master.port | quote }}
            - name: CBFS_MASTER_PROF
              value: {{ .Values.master.prof | quote }}
            - name: CBFS_MASTER_PEERS
              value: {{ include "cubefs.master.peers" . | quote }}
            - name: CBFS_MASTER_RETAIN_LOGS
              value: {{ .Values.master.retain_logs | quote }}
            - name: CBFS_MASTER_LOG_LEVEL
              value: {{ .Values.master.log_level | quote }}
            - name: CBFS_MASTER_EXPORTER_PORT
              value: {{ .Values.master.exporter_port | quote }}
            - name: CBFS_CONSUL_ADDR
              value: {{ tuple $envAll | include "cubefs.monitor.consul.url" | quote }}
            - name: CBFS_METANODE_RESERVED_MEM
              value: {{ .Values.master.metanode_reserved_mem | quote }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: cubefs-bin
              mountPath: /cfs/bin/config-master.sh
              subPath: config-master.sh
              readOnly: true
            - name: cubefs-conf
              mountPath: /cfs/conf
      containers:
        - name: master-pod
          image: {{ $.Values.image.server }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          command: [ "/bin/bash", "/cfs/bin/start.sh" ]
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
{{ tuple $envAll "port" .Values.master.port | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "prof" .Values.master.prof | include "helm-toolkit.utils.container_port" | indent 12 }}
{{ tuple $envAll "exporter-port" .Values.master.exporter_port | include "helm-toolkit.utils.container_port" | indent 12 }}
          volumeMounts:
            - name: cubefs-bin
              mountPath: /cfs/bin/start.sh
              subPath: start-master.sh
              readOnly: true
            - name: cubefs-conf
              mountPath: /cfs/conf
            {{- if $.Values.path.log }}
            - name: pod-log-path
              mountPath: /cfs/logs
              readOnly: false
            {{- end }}
            {{- if $.Values.path.data }}
            - name: pod-data-path
              mountPath: /cfs/data
              readOnly: false
            {{- end }}
{{ tuple $envAll $envAll.Values.master.resources | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
      volumes:
        - name: cubefs-bin
          configMap:
            name: cubefs-bin
            defaultMode: 0555
        - name: cubefs-conf
          emptyDir: { }
        {{- if $.Values.path.log }}
        - name: pod-log-path
          hostPath:
            path: {{ $.Values.path.log }}
        {{- end }}
        {{- if $.Values.path.data }}
        - name: pod-data-path
          hostPath:
            path: {{ $.Values.path.data }}
        {{- end }}
{{ end }}







