{{- if .Values.component.provisioner }}
{{- $envAll := . }}

{{- $consulAddress := tuple $envAll | include "cubefs.monitor.consul.address" }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cfs-sc
  
{{- if .Values.storageClass.default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: {{ $.Values.provisioner.dirver_name }}
reclaimPolicy: Delete
parameters:
  # Resource manager IP address or URL
  masterAddr: {{ include "cubefs.master-service.with.port" . | quote }}
  # Consul Service IP address or URL
  consulAddr: {{ $consulAddress | quote }}
  # Log level：debug, info, warn, error 
  logLevel: {{ $.Values.provisioner.log_level }}
---
{{ end }}



